.TH "Riferimenti per la directory /home/mikele/Documenti/Con2/Server/src" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Riferimenti per la directory /home/mikele/Documenti/Con2/Server/src
.SH SYNOPSIS
.br
.PP
.SS "File"

.in +1c
.ti -1c
.RI "file \fBaddUSER\&.c\fP"
.br
.RI "Funzione che permette la registrazione di un utente\&. "
.ti -1c
.RI "file \fBargSett\&.c\fP"
.br
.RI "Imposta una struct con gli argomenti da linea di comando\&. "
.ti -1c
.RI "file \fBfullread\&.c\fP"
.br
.RI "read() per socket "
.ti -1c
.RI "file \fBfullwrite\&.c\fP"
.br
.RI "write() per socket "
.ti -1c
.RI "file \fBgestConn\&.c\fP"
.br
.RI "Funzione per'istaurazione e la gestione della connessione\&. "
.ti -1c
.RI "file \fBiniSett\&.c\fP"
.br
.RI "inizzializza struct per i settaggi "
.ti -1c
.RI "file \fBIO\&.c\fP"
.br
.ti -1c
.RI "file \fBisdigit_in\&.c\fP"
.br
.RI "verifica input di monocaratteri numerici\&. "
.ti -1c
.RI "file \fBlog\&.c\fP"
.br
.ti -1c
.RI "file \fBmain_Server\&.c\fP"
.br
.ti -1c
.RI "file \fBmenuS\&.c\fP"
.br
.ti -1c
.RI "file \fBmodSettServ\&.c\fP"
.br
.RI "Modifica manualmente i settaggi del Server\&. "
.ti -1c
.RI "file \fBnewSocket\&.c\fP"
.br
.RI "Crea una comnessione TCP\&. "
.ti -1c
.RI "file \fBrwconf\&.c\fP"
.br
.RI "Lettura comando con conferma\&. "
.ti -1c
.RI "file \fBSave\&.c\fP"
.br
.ti -1c
.RI "file \fBServer\&.c\fP"
.br
.ti -1c
.RI "file \fBServer\&.h\fP"
.br
.RI "Header per le funzioni del Server\&. "
.ti -1c
.RI "file \fBsettPrint\&.c\fP"
.br
.RI "Stampa la tabella dei settaggi\&. "
.ti -1c
.RI "file \fBtestPath\&.c\fP"
.br
.RI "Testa l'esistenza di una directory\&. "
.ti -1c
.RI "file \fBverUser\&.c\fP"
.br
.RI "Funzione per il comando VER_USER\&. "
.ti -1c
.RI "file \fBwwconf\&.c\fP"
.br
.RI "Scrittura comando con conferma\&. "
.in -1c
