.TH "_SettSERVER" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SettSERVER
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "unsigned short \fBnPort\fP"
.br
.RI "numero di porta "
.ti -1c
.RI "int \fBnClientMax\fP"
.br
.RI "Numero di client massimi\&. "
.ti -1c
.RI "char \fBsaveDir\fP [PATH_MAX]"
.br
.RI "Cartella di salvataggio\&. "
.ti -1c
.RI "int \fBmaxBuffer\fP"
.br
.RI "Massimo buffer per lo scambio di dati\&. "
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 124 del file Server\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "int maxBuffer"

.PP
Massimo buffer per lo scambio di dati\&. 
.PP
Definizione alla linea 129 del file Server\&.h\&.
.SS "int nClientMax"

.PP
Numero di client massimi\&. 
.PP
Definizione alla linea 127 del file Server\&.h\&.
.SS "unsigned short nPort"

.PP
numero di porta 
.PP
Definizione alla linea 126 del file Server\&.h\&.
.SS "char saveDir[PATH_MAX]"

.PP
Cartella di salvataggio\&. 
.PP
Definizione alla linea 128 del file Server\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
