.TH "accounting" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accounting
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.h>\fP
.SS "Campi"

.in +1c
.ti -1c
.RI "unsigned \fBID\fP"
.br
.ti -1c
.RI "char \fBuser\fP [20]"
.br
.ti -1c
.RI "char \fBpass\fP [20]"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Definizione alla linea 137 del file Server\&.h\&.
.SH "Documentazione dei campi"
.PP 
.SS "unsigned ID"

.PP
Definizione alla linea 139 del file Server\&.h\&.
.SS "char pass[20]"

.PP
Definizione alla linea 141 del file Server\&.h\&.
.SS "char user[20]"

.PP
Definizione alla linea 140 del file Server\&.h\&.

.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
