.TH "/home/mikele/Documenti/Con2/Server/src/addUSER.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/addUSER.c \- Funzione che permette la registrazione di un utente\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBaddUser\fP (int sockfd)"
.br
.ti -1c
.RI "int \fBaddUser3\fP (char *name, char *pass)"
.br
.ti -1c
.RI "int \fBaddUser2\fP (int id, char *nomeUser, char *passUser)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Funzione che permette la registrazione di un utente\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione riceve da un client nome utente e password e li inserisce nel file degli utenti\&.
.PP
\fBParametri:\fP
.RS 4
\fIsockfd\fP riferito ad fd di una connessione TCP già stabilita
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Funzione fallita 
.br
\fI0\fP Nome utente e password registrati 
.br
\fI-1\fP Nome utente e password non registrati 
.RE
.PP

.PP
Definizione nel file \fBaddUSER\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int addUser (int sockfd)"

.PP
Definizione alla linea 19 del file addUSER\&.c\&.
.SS "int addUser2 (int id, char * nomeUser, char * passUser)"

.PP
Definizione alla linea 145 del file addUSER\&.c\&.
.SS "int addUser3 (char * name, char * pass)"

.PP
Definizione alla linea 93 del file addUSER\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
