.TH "/home/mikele/Documenti/Con2/Server/src/gestConn.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/gestConn.c \- Funzione per'istaurazione e la gestione della connessione\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBgestConn\fP ()"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Funzione per'istaurazione e la gestione della connessione\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione avvia il serve per ricevere connessioni dai client abilitati e ne gestisce gli aspetti\&.
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP FAILURE 
.br
\fI0\fP SUCCESS 
.RE
.PP

.PP
Definizione nel file \fBgestConn\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int gestConn ()"

.PP
Definizione alla linea 16 del file gestConn\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
