.TH "/home/mikele/Documenti/Con2/Server/src/IO.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/IO.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "size_t \fBfullread2\fP (int fd, void *buff, size_t count)"
.br
.ti -1c
.RI "size_t \fBfullwrite2\fP (int fd, const void *buff, size_t count)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "size_t fullread2 (int fd, void * buff, size_t count)"

.PP
Definizione alla linea 3 del file IO\&.c\&.
.SS "size_t fullwrite2 (int fd, const void * buff, size_t count)"

.PP
Definizione alla linea 31 del file IO\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
