.TH "/home/mikele/Documenti/Con2/Server/src/isdigit_in.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/isdigit_in.c \- verifica input di monocaratteri numerici\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBisdigit_in\fP (int *caracter)"
.br
.RI "Funzione con controllo e validazione dell'input da tastiera di un solo carattere numerico\&. Se è presenta quansiasi altro carattere, fallisce\&. "
.ti -1c
.RI "int \fBinputUInt\fP (unsigned int *result)"
.br
.RI "Funzione con controllo e validazione dell'input da tastiera di un valore unsigned int\&. @detail Se l'input ha altri caratteri, o è un valore oltre i limiti del compilatore fallisce la funzione\&. "
.ti -1c
.RI "int \fBinputInt\fP (int *result)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
verifica input di monocaratteri numerici\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione legge un input da stdin e veruififca se sia se un carattere numerico\&. A differenza di funzioni simili, non accetta spazi, o qualsiasi altro carattere in ingresso\&. L'unico input accettato e' un unico carattere numerico, il resto lo identifica come errore in input\&.
.PP
\fBParametri:\fP
.RS 4
\fI*caracter\fP puntatore a int per memorizzare il carattere\&.
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Funzione fallita\&. 
.br
\fI0\fP Input monocarattere numerico\&. 
.br
\fI1\fP Input non conforme\&. 
.RE
.PP

.PP
Definizione nel file \fBisdigit_in\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int inputInt (int * result)"

.PP
Definizione alla linea 139 del file isdigit_in\&.c\&.
.SS "int inputUInt (unsigned int * result)"

.PP
Funzione con controllo e validazione dell'input da tastiera di un valore unsigned int\&. @detail Se l'input ha altri caratteri, o è un valore oltre i limiti del compilatore fallisce la funzione\&. 
.PP
\fBParametri:\fP
.RS 4
\fI[OUT]\fP result Valore unsigned int dell'input 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Errore irreversibie 
.br
\fI1\fP Input non conforme 
.br
\fI0\fP Input Conforme 
.RE
.PP

.PP
Definizione alla linea 70 del file isdigit_in\&.c\&.
.SS "int isdigit_in (int * caracter)"

.PP
Funzione con controllo e validazione dell'input da tastiera di un solo carattere numerico\&. Se è presenta quansiasi altro carattere, fallisce\&. 
.PP
\fBParametri:\fP
.RS 4
\fI[OUT]\fP caracter valore intero del numero immesso in ingresso 
.RE
.PP
\fBRestituisce:\fP
.RS 4
Verifica della funzione 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Errore irreversibie 
.br
\fI1\fP Input non conforme 
.br
\fI0\fP Input Conforme 
.RE
.PP

.PP
Definizione alla linea 22 del file isdigit_in\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
