.TH "/home/mikele/Documenti/Con2/Server/src/log.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/log.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBlogF\fP (int *fd)"
.br
.ti -1c
.RI "int \fBclosedd\fP (int *fd)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "const char \fBnameLog\fP [20] ='\&./log/log\&.txt'"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int closedd (int * fd)"

.PP
Definizione alla linea 23 del file log\&.c\&.
.SS "int logF (int * fd)"

.PP
Definizione alla linea 5 del file log\&.c\&.
.SH "Documentazione delle variabili"
.PP 
.SS "const char nameLog[20] ='\&./log/log\&.txt'"

.PP
Definizione alla linea 3 del file log\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
