.TH "/home/mikele/Documenti/Con2/Server/src/menuS.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/menuS.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "*author Cannavo Michele *[046002210] date *file funcPrint c *brief Funzioni per la stampa di informazioni di FILDERX *version *copyright Licenza GPL *details File contenente l Header per le funzione di stampa di FILDERX int \fBmenServ\fP ()"
.br
.ti -1c
.RI "int \fBmenSett\fP ()"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "* author Cannavo Michele* [046002210] date* file funcPrint c* brief Funzioni per la stampa di informazioni di FILDERX* version* copyright Licenza GPL* details File contenente l Header per le funzione di stampa di FILDERX int menServ ()"

.PP
Definizione alla linea 31 del file menuS\&.c\&.
.SS "int menSett ()"

.PP
Definizione alla linea 80 del file menuS\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
