.TH "/home/mikele/Documenti/Con2/Server/src/modSettServ.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/modSettServ.c \- Modifica manualmente i settaggi del Server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmodSettServ\fP ()"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Modifica manualmente i settaggi del Server\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione permette la modifica manuale dei settaggi del server Per ogni parametro è possibile specificarne uno nuovo\&. Se non lo si vuole cambiare basterà non scrivere nulla, se si scrive un parametro errato, esso non verrà modificato
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Fallimento funzione 
.br
\fI0\fP Settaggi modiifcati 
.RE
.PP

.PP
Definizione nel file \fBmodSettServ\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int modSettServ ()"

.PP
Definizione alla linea 18 del file modSettServ\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
