.TH "/home/mikele/Documenti/Con2/Server/src/newSocket.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/newSocket.c \- Crea una comnessione TCP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBnewSocket\fP (int *sock_fd, unsigned short port, unsigned long addr)"
.br
.ti -1c
.RI "int \fBclosefd\fP (int *sock_fd)"
.br
.ti -1c
.RI "int \fBcloseSocket\fP (int *sock_fd)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "int \fBserver_sockfd\fP =\-1"
.br
.ti -1c
.RI "int \fBclient_sockfd\fP =\-1"
.br
.ti -1c
.RI "const char * \fB_COMMAND_\fP []"
.br
.RI "Array di sctringhe con i comandi\&. "
.in -1c
.SH "Descrizione dettagliata"
.PP 
Crea una comnessione TCP\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione crea un socket AF_INET, SOCK_STREAM, TCP
.PP
\fBParametri:\fP
.RS 4
\fI*sock_fd\fP puntatore ad int per il file descriptor del socket 
.br
\fIport\fP porta in ascolto del socket 
.br
\fIaddr\fP Indirizzo del socket
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Errore nella funzione 
.br
\fI0\fP Socket creato 
.RE
.PP

.PP
Definizione nel file \fBnewSocket\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int closefd (int * sock_fd)"

.PP
Definizione alla linea 90 del file newSocket\&.c\&.
.SS "int closeSocket (int * sock_fd)"

.PP
Definizione alla linea 124 del file newSocket\&.c\&.
.SS "int newSocket (int * sock_fd, unsigned short port, unsigned long addr)"

.PP
Definizione alla linea 28 del file newSocket\&.c\&.
.SH "Documentazione delle variabili"
.PP 
.SS "* _COMMAND_"
\fBValore iniziale:\fP
.PP
.nf
={
    "VER_USER",
    "ADD_USER",
    "RES_FILE",
    "REQ_FILE",
}
.fi
.PP
Array di sctringhe con i comandi\&. 
.PP
Definizione alla linea 5 del file newSocket\&.c\&.
.SS "int client_sockfd =\-1"

.PP
Definizione alla linea 4 del file newSocket\&.c\&.
.SS "int server_sockfd =\-1"

.PP
Definizione alla linea 3 del file newSocket\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
