.TH "/home/mikele/Documenti/Con2/Server/src/Save.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/Save.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmainWrite\fP (int id, const char *nomeUser, const char *passUser)"
.br
.ti -1c
.RI "int \fBmainRead\fP ()"
.br
.ti -1c
.RI "*********************************************************************int \fBmainVer\fP (int id, const char *name, const char *pass)"
.br
.in -1c
.SH "Documentazione delle funzioni"
.PP 
.SS "int mainRead ()"

.PP
Definizione alla linea 37 del file Save\&.c\&.
.SS "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * int mainVer (int id, const char * name, const char * pass)"

.PP
Definizione alla linea 61 del file Save\&.c\&.
.SS "int mainWrite (int id, const char * nomeUser, const char * passUser)"

.PP
Definizione alla linea 3 del file Save\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
