.TH "/home/mikele/Documenti/Con2/Server/src/Server.h" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/Server.h \- Header per le funzioni del Server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Strutture dati"

.in +1c
.ti -1c
.RI "struct \fB_SettSERVER\fP"
.br
.ti -1c
.RI "struct \fBaccounting\fP"
.br
.in -1c
.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBDECIMO_UINT\fP   ((UINT_MAX)/10)"
.br
.RI "A1/10 del valore di UNIT_MAX\&. "
.ti -1c
.RI "#define \fBUNITA_UINT\fP   ((UINT_MAX)\-((\fBDECIMO_UINT\fP)*10))"
.br
.RI "Valore dell'unita' di UINT_MAX\&. "
.ti -1c
.RI "#define \fBDECIMO_INT\fP   (INT_MAX / 10)"
.br
.RI "1/10 del valore di INT_MAX "
.ti -1c
.RI "#define \fBUNITAP\fP   ((INT_MAX) \- (\fBDECIMO_INT\fP *10))"
.br
.RI "Valore dell'unita' di INT_MAX\&. "
.ti -1c
.RI "#define \fBUNITAN\fP   (\fBUNITAP\fP + 1)"
.br
.RI "Valore dell'unita' di INT_MIN\&. "
.ti -1c
.RI "#define \fBMAX_CHAR_USER\fP   20"
.br
.RI "Valore di caratteri massimo del nome utente\&. "
.ti -1c
.RI "#define \fBMAX_CHAR_PASS\fP   20"
.br
.RI "Valore di caratteri massimo del nome utente\&. "
.ti -1c
.RI "#define \fBPORT\fP   64000"
.br
.RI "Porta in ascolto del Server\&. "
.ti -1c
.RI "#define \fBMAX_CLIENT\fP   5"
.br
.RI "Numero massimo di connessioni simultanee possibili\&. "
.ti -1c
.RI "#define \fBSAVEDIR\fP   '/Scaricati'"
.br
.RI "Percorso relativo dalla home per la cartella di salvataggio\&. "
.ti -1c
.RI "#define \fBMAXBUF\fP   1024"
.br
.RI "Valore massimo del buffer per lo scambio di dati col client\&. "
.ti -1c
.RI "#define \fBSBUFFER\fP"
.br
.RI "Macro di puizia del buffer stdin\&. "
.ti -1c
.RI "#define \fBVER_USER\fP   \fB_COMMAND_\fP[0]"
.br
.RI "Comando per la verifica dell'utente\&. "
.ti -1c
.RI "#define \fBADD_USER\fP   \fB_COMMAND_\fP[1]"
.br
.RI "Comando per la registrazione\&. "
.ti -1c
.RI "#define \fBRES_USER\fP   \fB_COMMAND_\fP[2]"
.br
.ti -1c
.RI "#define \fBREQ_USER\fP   \fB_COMMAND_\fP[3]"
.br
.in -1c
.SS "Ridefinizioni di tipo (typedef)"

.in +1c
.ti -1c
.RI "typedef struct \fB_SettSERVER\fP \fBSettSERVER\fP"
.br
.ti -1c
.RI "typedef struct \fBaccounting\fP \fBUSER_FILDERX\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmainWrite\fP (int id, const char *nomeUser, const char *passUser)"
.br
.ti -1c
.RI "int \fBmainRead\fP ()"
.br
.ti -1c
.RI "int \fBmainVer\fP (int id, const char *name, const char *pass)"
.br
.ti -1c
.RI "size_t \fBfullread\fP (int fd, void *buff, size_t count)"
.br
.ti -1c
.RI "size_t \fBfullwrite\fP (int fd, const void *buff, size_t count)"
.br
.ti -1c
.RI "int \fBisdigit_in\fP (int *caracter)"
.br
.RI "Funzione con controllo e validazione dell'input da tastiera di un solo carattere numerico\&. Se è presenta quansiasi altro carattere, fallisce\&. "
.ti -1c
.RI "int \fBinputUInt\fP (unsigned int *result)"
.br
.RI "Funzione con controllo e validazione dell'input da tastiera di un valore unsigned int\&. @detail Se l'input ha altri caratteri, o è un valore oltre i limiti del compilatore fallisce la funzione\&. "
.ti -1c
.RI "int \fBinputInt\fP (int *result)"
.br
.ti -1c
.RI "int \fBtestPath\fP (char *wPath)"
.br
.ti -1c
.RI "int \fBrwconf\fP (int sockfd, void *buff, int size)"
.br
.ti -1c
.RI "int \fBwwconf\fP (int sockfd, void *buff, int size)"
.br
.ti -1c
.RI "int \fBmyMainS\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "int \fBiniSett\fP ()"
.br
.ti -1c
.RI "int \fBargSett\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "int \fBmenServ\fP ()"
.br
.ti -1c
.RI "int \fBmenSett\fP ()"
.br
.ti -1c
.RI "int \fBmenAcc\fP ()"
.br
.ti -1c
.RI "void \fBsettPrint\fP (int fdStream)"
.br
.ti -1c
.RI "int \fBmodSettServ\fP ()"
.br
.ti -1c
.RI "int \fBgestConn\fP ()"
.br
.ti -1c
.RI "int \fBnewSocket\fP (int *sockfd, unsigned short port, unsigned long TYPEIP)"
.br
.ti -1c
.RI "int \fBclosefd\fP (int *sockfd)"
.br
.ti -1c
.RI "int \fBverUser\fP (int id)"
.br
.ti -1c
.RI "int \fBverUser2\fP (const char *name, const char *pass)"
.br
.ti -1c
.RI "int \fBaddUser2\fP (int id, char *name, char *pass)"
.br
.ti -1c
.RI "int \fBaddUser\fP (int sockfd)"
.br
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "const char * \fB_COMMAND_\fP []"
.br
.RI "Array di sctringhe con i comandi\&. "
.ti -1c
.RI "\fBSettSERVER\fP * \fBsettaggi\fP"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Header per le funzioni del Server\&. 


.PP
 
.PP
\fBAutore:\fP
.RS 4
Cannavo Michele
.RE
.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questo è un header file cumulativo per tutte le funzioni del Server FILDERX 
.PP
Definizione nel file \fBServer\&.h\fP\&.
.SH "Documentazione delle definizioni"
.PP 
.SS "#define ADD_USER   \fB_COMMAND_\fP[1]"

.PP
Comando per la registrazione\&. 
.PP
Definizione alla linea 112 del file Server\&.h\&.
.SS "#define DECIMO_INT   (INT_MAX / 10)"

.PP
1/10 del valore di INT_MAX 
.PP
Definizione alla linea 44 del file Server\&.h\&.
.SS "#define DECIMO_UINT   ((UINT_MAX)/10)"

.PP
A1/10 del valore di UNIT_MAX\&. 
.PP
Definizione alla linea 32 del file Server\&.h\&.
.SS "#define MAX_CHAR_PASS   20"

.PP
Valore di caratteri massimo del nome utente\&. 
.PP
Definizione alla linea 66 del file Server\&.h\&.
.SS "#define MAX_CHAR_USER   20"

.PP
Valore di caratteri massimo del nome utente\&. 
.PP
Definizione alla linea 65 del file Server\&.h\&.
.SS "#define MAX_CLIENT   5"

.PP
Numero massimo di connessioni simultanee possibili\&. 
.PP
Definizione alla linea 82 del file Server\&.h\&.
.SS "#define MAXBUF   1024"

.PP
Valore massimo del buffer per lo scambio di dati col client\&. 
.PP
Definizione alla linea 84 del file Server\&.h\&.
.SS "#define PORT   64000"

.PP
Porta in ascolto del Server\&. 
.PP
Definizione alla linea 81 del file Server\&.h\&.
.SS "#define REQ_USER   \fB_COMMAND_\fP[3]"

.PP
Definizione alla linea 114 del file Server\&.h\&.
.SS "#define RES_USER   \fB_COMMAND_\fP[2]"

.PP
Definizione alla linea 113 del file Server\&.h\&.
.SS "#define SAVEDIR   '/Scaricati'"

.PP
Percorso relativo dalla home per la cartella di salvataggio\&. 
.PP
Definizione alla linea 83 del file Server\&.h\&.
.SS "#define SBUFFER"
\fBValore:\fP
.PP
.nf
do{int ch; \
                    while ( ( ch=getchar() ) !='\n' && (ch != EOF) );\
                }while(0)
.fi
.PP
Macro di puizia del buffer stdin\&. 
.PP
Definizione alla linea 90 del file Server\&.h\&.
.SS "#define UNITA_UINT   ((UINT_MAX)\-((\fBDECIMO_UINT\fP)*10))"

.PP
Valore dell'unita' di UINT_MAX\&. 
.PP
Definizione alla linea 38 del file Server\&.h\&.
.SS "#define UNITAN   (\fBUNITAP\fP + 1)"

.PP
Valore dell'unita' di INT_MIN\&. 
.PP
Definizione alla linea 56 del file Server\&.h\&.
.SS "#define UNITAP   ((INT_MAX) \- (\fBDECIMO_INT\fP *10))"

.PP
Valore dell'unita' di INT_MAX\&. 
.PP
Definizione alla linea 50 del file Server\&.h\&.
.SS "#define VER_USER   \fB_COMMAND_\fP[0]"

.PP
Comando per la verifica dell'utente\&. 
.PP
Definizione alla linea 111 del file Server\&.h\&.
.SH "Documentazione delle ridefinizioni di tipo (typedef)"
.PP 
.SS "typedef struct \fB_SettSERVER\fP \fBSettSERVER\fP"

.PP
Definizione alla linea 132 del file Server\&.h\&.
.SS "typedef struct \fBaccounting\fP \fBUSER_FILDERX\fP"

.PP
Definizione alla linea 143 del file Server\&.h\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int addUser (int sockfd)"

.PP
Definizione alla linea 19 del file addUSER\&.c\&.
.SS "int addUser2 (int id, char * name, char * pass)"

.PP
Definizione alla linea 145 del file addUSER\&.c\&.
.SS "int argSett (int argc, char * argv[])"

.PP
Definizione alla linea 21 del file argSett\&.c\&.
.SS "int closefd (int * sockfd)"

.PP
Definizione alla linea 90 del file newSocket\&.c\&.
.SS "size_t fullread (int fd, void * buff, size_t count)"

.PP
Definizione alla linea 21 del file fullread\&.c\&.
.SS "size_t fullwrite (int fd, const void * buff, size_t count)"

.PP
Definizione alla linea 21 del file fullwrite\&.c\&.
.SS "int gestConn ()"

.PP
Definizione alla linea 16 del file gestConn\&.c\&.
.SS "int iniSett ()"

.PP
Definizione alla linea 19 del file iniSett\&.c\&.
.SS "int inputInt (int * result)"

.PP
Definizione alla linea 139 del file isdigit_in\&.c\&.
.SS "int inputUInt (unsigned int * result)"

.PP
Funzione con controllo e validazione dell'input da tastiera di un valore unsigned int\&. @detail Se l'input ha altri caratteri, o è un valore oltre i limiti del compilatore fallisce la funzione\&. 
.PP
\fBParametri:\fP
.RS 4
\fI[OUT]\fP result Valore unsigned int dell'input 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Errore irreversibie 
.br
\fI1\fP Input non conforme 
.br
\fI0\fP Input Conforme 
.RE
.PP

.PP
Definizione alla linea 70 del file isdigit_in\&.c\&.
.SS "int isdigit_in (int * caracter)"

.PP
Funzione con controllo e validazione dell'input da tastiera di un solo carattere numerico\&. Se è presenta quansiasi altro carattere, fallisce\&. 
.PP
\fBParametri:\fP
.RS 4
\fI[OUT]\fP caracter valore intero del numero immesso in ingresso 
.RE
.PP
\fBRestituisce:\fP
.RS 4
Verifica della funzione 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP Errore irreversibie 
.br
\fI1\fP Input non conforme 
.br
\fI0\fP Input Conforme 
.RE
.PP

.PP
Definizione alla linea 22 del file isdigit_in\&.c\&.
.SS "int mainRead ()"

.PP
Definizione alla linea 37 del file Save\&.c\&.
.SS "int mainVer (int id, const char * name, const char * pass)"

.PP
Definizione alla linea 61 del file Save\&.c\&.
.SS "int mainWrite (int id, const char * nomeUser, const char * passUser)"

.PP
Definizione alla linea 3 del file Save\&.c\&.
.SS "int menAcc ()"

.SS "int menServ ()"

.PP
Definizione alla linea 31 del file menuS\&.c\&.
.SS "int menSett ()"

.PP
Definizione alla linea 80 del file menuS\&.c\&.
.SS "int modSettServ ()"

.PP
Definizione alla linea 18 del file modSettServ\&.c\&.
.SS "int myMainS (int argc, char * argv[])"

.PP
Definizione alla linea 16 del file main_Server\&.c\&.
.SS "int newSocket (int * sockfd, unsigned short port, unsigned long TYPEIP)"

.PP
Definizione alla linea 28 del file newSocket\&.c\&.
.SS "int rwconf (int sockfd, void * buff, int size)"

.PP
Definizione alla linea 21 del file rwconf\&.c\&.
.SS "void settPrint (int fdStream)"

.PP
Definizione alla linea 19 del file settPrint\&.c\&.
.SS "int testPath (char * wPath)"

.PP
Definizione alla linea 22 del file testPath\&.c\&.
.SS "int verUser (int id)"

.PP
Definizione alla linea 19 del file verUser\&.c\&.
.SS "int verUser2 (const char * name, const char * pass)"

.PP
Definizione alla linea 84 del file verUser\&.c\&.
.SS "int wwconf (int sockfd, void * buff, int size)"

.PP
Definizione alla linea 20 del file wwconf\&.c\&.
.SH "Documentazione delle variabili"
.PP 
.SS "const char* _COMMAND_[]"

.PP
Array di sctringhe con i comandi\&. 
.PP
Definizione alla linea 5 del file newSocket\&.c\&.
.SS "\fBSettSERVER\fP* settaggi"

.PP
Definizione alla linea 14 del file main_Server\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
