.TH "/home/mikele/Documenti/Con2/Server/src/settPrint.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/settPrint.c \- Stampa la tabella dei settaggi\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "void \fBsettPrint\fP (int fdStream)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Stampa la tabella dei settaggi\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione stampa su un file aperto tramite un file descriptor, una tabella contenete le attuali impostazione del Server\&. La funzione e' utilizzabile sia per lo stream stdin sia per un normale file di testo\&.
.PP
\fBParametri:\fP
.RS 4
\fIfdStream\fP Fd del file in cui si vogiono stampare i settaggi
.RE
.PP
\fBRestituisce:\fP
.RS 4
Non ritorna valori 
.RE
.PP

.PP
Definizione nel file \fBsettPrint\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "void settPrint (int fdStream)"

.PP
Definizione alla linea 19 del file settPrint\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
