.TH "/home/mikele/Documenti/Con2/Server/src/verUser.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/verUser.c \- Funzione per il comando VER_USER\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBverUser\fP (int sockfd)"
.br
.ti -1c
.RI "int \fBverUser2\fP (const char *name, const char *pass)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Funzione per il comando VER_USER\&. 


.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
Questa funzione gestisce le operazioni da effettuare quando il server riceve il comando di VER_USER\&. Questo comando richiede al server di verificare l'autorizzazzione da parte di un client ad utilizzare le funzione del Server\&.
.PP
\fBParametri:\fP
.RS 4
\fIsockfd\fP file descriptor del socket
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP FAILURE 
.br
\fI0\fP SUCCESS 
.RE
.PP

.PP
Definizione nel file \fBverUser\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int verUser (int sockfd)"

.PP
Definizione alla linea 19 del file verUser\&.c\&.
.SS "int verUser2 (const char * name, const char * pass)"

.PP
Definizione alla linea 84 del file verUser\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
