.TH "/home/mikele/Documenti/Con2/Server/src/wwconf.c" 3 "Sab 19 Gen 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Documenti/Con2/Server/src/wwconf.c \- Scrittura comando con conferma\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br

.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBwwconf\fP (int sockfd, void *buff, int size)"
.br
.in -1c
.SH "Descrizione dettagliata"
.PP 
Scrittura comando con conferma\&. 


.PP
.PP
\fBVersione:\fP
.RS 4
1\&.0
.RE
.PP
\fBParametri:\fP
.RS 4
\fIsockfd\fP file descriptor del socket 
.br
\fIbuff\fP buffer che continene il comando 
.br
\fIsize\fP Dimensione del buffer
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fI-1\fP FAILURE 
.br
\fI0\fP SUCCESS
.RE
.PP
Questa funzione scrive un comando in un socket e dopo invia la conferma della lettura\&. Serve per sincronizzare server e client\&. 
.PP
Definizione nel file \fBwwconf\&.c\fP\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int wwconf (int sockfd, void * buff, int size)"

.PP
Definizione alla linea 20 del file wwconf\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per My Project a partire dal codice sorgente\&.
