.TH "/home/mikele/Scrivania/Univ/Sistemi Opeativi/Progetto-SistemiOperatini/Consegna1.c" 3 "Sab 1 Dic 2018" "Version v0.3" "Pro.OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Scrivania/Univ/Sistemi Opeativi/Progetto-SistemiOperatini/Consegna1.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br

.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBDEBUG_\fP"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBgetNCore\fP (long *\fBnCore\fP)"
.br
.RI "La funzione legge dal file /proc/cinfo l'informazione richiesta\&. "
.ti -1c
.RI "int \fBtestPath\fP (char *wPath)"
.br
.RI "Verifica se una stringa corrisponda ad una directory\&. "
.in -1c
.SS "Variabili"

.in +1c
.ti -1c
.RI "long \fBnCore\fP =0"
.br
.ti -1c
.RI "char \fBworkPath\fP [PATH_MAX] ='~/'"
.br
.in -1c
.SH "Documentazione delle definizioni"
.PP 
.SS "#define DEBUG_"
Macro per un primo debug 
.PP
Definizione alla linea 30 del file Consegna1\&.c\&.
.SH "Documentazione delle funzioni"
.PP 
.SS "int getNCore (long * nCore)"

.PP
La funzione legge dal file /proc/cinfo l'informazione richiesta\&. 
.PP
\fBParametri:\fP
.RS 4
\fI*nCore\fP Numero di core di un processore 
.RE
.PP
\fBRestituisce:\fP
.RS 4
Successo della funzione 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fIEXIT_SUCCESS\fP Riuscita della funzione 
.br
\fIEXIT_FAILURE\fP Insucesso della funzione 
.RE
.PP

.PP
Definizione alla linea 106 del file Consegna1\&.c\&.
.SS "int testPath (char * wPath)"

.PP
Verifica se una stringa corrisponda ad una directory\&. 
.PP
\fBParametri:\fP
.RS 4
\fIwPath\fP stringa contenete il Path 
.RE
.PP
\fBRestituisce:\fP
.RS 4
Successo della funzione 
.RE
.PP
\fBValori di ritorno:\fP
.RS 4
\fIEXIT_SUCCESS\fP Riuscita della funzione 
.br
\fIEXIT_FAILURE\fP Insucesso della funzione 
.RE
.PP

.PP
Definizione alla linea 118 del file Consegna1\&.c\&.
.SH "Documentazione delle variabili"
.PP 
.SS "long nCore =0"

.PP
Definizione alla linea 21 del file Consegna1\&.c\&.
.SS "char workPath[PATH_MAX] ='~/'"

.PP
Definizione alla linea 22 del file Consegna1\&.c\&.
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per Pro\&.OS a partire dal codice sorgente\&.
