.TH "md__home_mikele__scrivania__univ__sistemi__opeativi__progetto-_sistemi_operatini__r_e_a_d_m_e" 3 "Sab 1 Dic 2018" "Version v0.3" "Pro.OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_mikele__scrivania__univ__sistemi__opeativi__progetto-_sistemi_operatini__r_e_a_d_m_e \- \fI\fBProgetto-SistemiOperativi\fP\fP 

.PP
.PP
**_Cannavo' Michele - Matr\&. O46-002210_**
.PP
.PP
.PP
.SS "## Consegna1 "
.PP
.SS "**1) Elenco funzioni**"
.PP
\fBNOME\fP  \fBDESCRIZIONE\fP   \fB\fBtestPath()\fP\fP  \fITesta se la cartella iniziale esiste\fP   \fB\fBgetNCore()\fP\fP  \fIReperisce il numero dei core di un processore\fP   
