.TH "/home/mikele/Scrivania/Univ/Sistemi Opeativi/Progetto-SistemiOperatini/README.md" 3 "Sab 1 Dic 2018" "Version v0.3" "Pro.OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mikele/Scrivania/Univ/Sistemi Opeativi/Progetto-SistemiOperatini/README.md
.SH SYNOPSIS
.br
.PP
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per Pro\&.OS a partire dal codice sorgente\&.
